import { Processor, WorkerHost } from '@nestjs/bullmq';
import { Job } from 'bullmq';
import { PrismaService } from '../prisma/prisma.service';

interface BlogSummaryJobData {
  blogId: string;
  content: string;
}

@Processor('blog-summary')
export class BlogSummaryProcessor extends WorkerHost {
  constructor(private readonly prisma: PrismaService) {
    super();
  }

  async process(job: Job<BlogSummaryJobData, string, string>): Promise<string> {
    const { blogId, content } = job.data;

    console.log(`[Job Started] Generating summary for blog ${blogId}...`);

    const generatedSummary =
      content.substring(0, 100) + '... (Auto-generated by background job)';

    await this.prisma.blog.update({
      where: { id: blogId },
      data: { summary: generatedSummary },
    });

    console.log(`[Job Complete] Summary saved for blog ${blogId}`);
    return generatedSummary;
  }
}
